---
- name: Testing
  hosts: ec2_user
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - update
#    - install
    - project
    - mysql
#    - test
    - finish
