---
###- name: Set root user password
###  mysql_user:
###    login_unix_socket: "/data/db/mysql/mysql.sock"
###    name: root
###    host: localhost
###    password: "{{ mysql_root_pass }}"
###    check_implicit_admin: true
###  become: yes
###  ignore_errors: true

##- name: MySQL | Creating MySQL Live DB
##  mysql_db:
##   name: "{{ mysql_live_db }}"
##   login_host: "localhost"
##   login_user: "root"
##   login_password: "{{ mysql_root_pass }}"
##   state: present
##  become: yes
##  ignore_errors: true
##
##- name: MySQL | Live User Setup
##  mysql_user:
##   name: "{{ mysql_live_user }}"
##   password: "{{ mysql_live_pass }}"
##   host: 'localhost'
##   priv: '{{ mysql_live_db }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,CREATE VIEW,EVENT,TRIGGER,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE'
##   state: present
##   login_host: "localhost"
##   login_user: "root"
##   login_password: "{{ mysql_root_pass }}"
##  become: yes
##  ignore_errors: true

- name: MySQL | Creating MySQL UAT DB
  mysql_db:
    name: "{{ mysql_uat_db }}"
    login_host: "localhost"
    login_user: "root"
    login_password: "{{ mysql_root_pass }}"
    state: present
  become: yes
  ignore_errors: true

- name: MySQL | UAT User Setup
  mysql_user:
    name: "{{ mysql_uat_user }}"
    password: "{{ mysql_uat_pass }}"
    login_host: "localhost"
    login_user: "root"
    login_password: "{{ mysql_root_pass }}"
    host: 'localhost'
    priv: '{{ mysql_uat_db }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,CREATE VIEW,EVENT,TRIGGER,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE'
    state: present
  become: yes
  ignore_errors: true
